backend:
  name: git-gateway
  branch: master # Branch to update
  squash_merges: true
publish_mode: editorial_workflow
media_folder: "/assets/images/cms_uploads" 
site_url: https://haxorg.io
display_url: https://haxorg.io
logo_url: https://haxorg.io/assets/images/haxlogo1.png
collections:
  - name: "bios"
    label: "Bio"
    description: "List of all of our team members in the Our Team page. New bios must be approved by the website team."
    folder: "_bios"
    create: true
    slug: "{{slug}}"
    preview_path: "our-team"
    identifier_field: "name"
    editor:
      preview: false
    fields:
      - {label: "Order", name: "order", widget: "hidden", default: 100} # so it gets put at the end, not the beginning
      - {label: "Name", name: "name", widget: "string", hint: "Your full name"}
      - {label: "Position", name: "position", widget: "string", hint: "Your position, in title case. e.g. Director of Outreach; Member of Design and Content Creation, etc."}
      - {label: "Description - directors only", name: "description", widget: "text", required: false, hint: "DIRECTORS ONLY: 3-5 sentence bio about yourself and your interests"}
      - {label: "Profile Picture", name: "image_url", widget: "image", hint: "Upload a SQUARE image of yourself"}
      - {label: "Email", name: "email", widget: "string", required: false, hint: "Just include an email. No need to include a mailto at the front."}
      - {label: "Instagram URL", name: "instagram", widget: "string", required: false, hint: "Links, not usernames"}
      - {label: "LinkedIn URL", name: "linkedin", widget: "string", required: false, hint: "Links, not usernames"}
      - {label: "Website URL", name: "website", widget: "string", required: false, hint: "Links, not usernames"}
      - {label: "Facebook URL", name: "facebook", widget: "string", required: false, hint: "Links, not usernames"}
      - {label: "Twitter URL", name: "twitter", widget: "string", required: false, hint: "Links, not usernames"}
      - {label: "Youtube URL", name: "youtube", widget: "string", required: false, hint: "Links, not usernames"}
      - {label: "Github URL", name: "github", widget: "string", required: false, hint: "Links, not usernames"}
      - {label: "Discord URL", name: "discord", widget: "string", required: false, hint: "Links, not usernames"}
      - {label: "Snapchat URL", name: "snapchat", widget: "string", required: false, hint: "Links, not usernames"}