backend:
  name: git-gateway
  branch: staging # Branch to update
  squash_merges: true
publish_mode: editorial_workflow
media_folder: "/assets/images/cms_uploads" 
site_url: https://haxorg.io
display_url: https://haxorg.io
logo_url: https://haxorg.io/assets/images/haxlogo1.png
collections:
  - name: "bios"
    label: "Bio"
    description: "List of all of our team members in the Our Team page. Bios are sorted by position (director vs. member) and then alphabetically. New bios must be approved by the website team."
    folder: "_bios"
    create: true
    slug: "{{slug}}"
    preview_path: "our-team"
    identifier_field: "name"
    editor:
      preview: false
    fields:
      - {label: "Order", name: "order", widget: "hidden", default: 5} # people are generally not directors? web team will manually edit if they are
      - {label: "Name", name: "name", widget: "string", hint: "Your full name"}
      - {label: "Position", name: "position", widget: "string", hint: "In title case. e.g. Director of X; Member of X; Member of X and Y; Member of X, Y, and Z"}
      - {label: "Description - directors only", name: "description", widget: "text", required: false, hint: "DIRECTORS ONLY: 3-5 sentence bio about yourself and your interests"}
      - {label: "Profile Picture", name: "image_url", widget: "image", hint: "Upload a SQUARE image of yourself"}
      - {label: "Email", name: "email", widget: "string", required: false, hint: "Just include an email. No need to include a mailto at the front."}
      - {label: "Instagram URL", name: "instagram", widget: "string", required: false, hint: "Links, not usernames"}
      - {label: "LinkedIn URL", name: "linkedin", widget: "string", required: false, hint: "Links, not usernames"}
      - {label: "Website URL", name: "website", widget: "string", required: false, hint: "Links, not usernames"}
      - {label: "Facebook URL", name: "facebook", widget: "string", required: false, hint: "Links, not usernames"}
      - {label: "Twitter URL", name: "twitter", widget: "string", required: false, hint: "Links, not usernames"}
      - {label: "Youtube URL", name: "youtube", widget: "string", required: false, hint: "Links, not usernames"}
      - {label: "Github URL", name: "github", widget: "string", required: false, hint: "Links, not usernames"}
      - {label: "Discord URL", name: "discord", widget: "string", required: false, hint: "Links, not usernames"}
      - {label: "Snapchat URL", name: "snapchat", widget: "string", required: false, hint: "Links, not usernames"}
  - name: "events"
    label: "Event"
    description: "A list of HAX-affiliated events, upcoming and past."
    folder: "_events"
    create: true
    slug: "{{slug}}"
    preview_path: "events"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string", hint: "Name of the event."}
      - {label: "Date", name: "date", widget: "date", hint: "If you set the date in the future, the event will appear as upcoming, and if you set it in the past, it'll appear under past events."}
      - {label: "Location", name: "location", widget: "string", hint: "For places in the US: City, State; For places outside the US: City, Country"}
      - {label: "Cover", name: "cover", widget: "image", hint: "Upload an image. On the site, the image appears as 250px in height, while the width varies with the screen size."}
      - {label: "Website URL", name: "website_url", widget: "string", hint: "Link to main website of the event."}
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    description: "Blog posts"
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "blog/{{year}}/{{month}}/{{day}}/{{title}}"
    summary: "{{title}}"
    editor:
      preview: false # Since it looked weird
    # All fields default to required unless specified
    fields: # The front matter for each post
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", hint: "Title of the post."}
      - {label: "Subheading", name: "subheading", widget: "text", hint: "Short description (1-2 sentences) of the post content. Appears underneath the title."}
      - {label: "Tags", name: "tags", widget: "string", hint: "Keywords which are associated with the post. Separate with spaces."}
      - {label: "Publish Date", name: "date", widget: "date", hint: "If you set the date in the future, the post will only appear on the site on that date."}
      - {label: "Featured Image", name: "cover", widget: "image", hint: "Appears in the thumbnail and also the top of the post page."}
      - {label: "HAX Author", name: "author", widget: "string", hint: "Full name of the author only if the author is a member of HAX. Must exactly match the name under Our Team, case sensitive."}
      - {label: "Guest Author", name: "guest_author", widget: "boolean", default: false, required: false, hint: "Enable only if the post is by a guest author. If this is enabled and a HAX author is specified, this will supersede the HAX author."}
      - {label: "Guest Author Name", name: "guest_author_name", widget: "string", required: false , hint: "Name of the guest author."}
      - {label: "Guest Author Description", name: "guest_author_desc", widget: "string", required: false, hint: "Short description (1-2 sentences) of the guest author." }
      - {label: "Body", name: "body", widget: "markdown"}